### ISSUE TITLE
Description for argument of register method is less rigorous

### ISSUE THREAD

**Issue by wanghongjuan** [01org/iot-js-api#27]
According to [specification](https://github.com/01org/iot-js-api/blob/master/api/ocf/server.md), describe the argument resource of [`register`](https://github.com/01org/iot-js-api/blob/master/api/ocf/server.md#register) method as below:
```
The resource argument is an object that should contain at least the following properties (other resource properties may also be specified): resourcePath and resourceTypes
```
I noticed that the key word is "should", but I think "must" more suit this situation. If implementation is right, there is another basic property `interfaces` is required, just like `resourcePath` and `resourceType`. Test [`Server - register and unregister resource.js`](https://github.com/01org/iot-js-api/blob/master/tests/Server%20-%20register%20and%20unregister%20resource.js#L65) has prove that the resource object must contain at least the three properties as above, otherwise failed to create resource. What do you think about it?

For [`resource`] object, except properties `slow` and `properties` are optional, other properties are required. My understanding is when using `resource` dictionary for creating or registering resource, the required properties must be setting, if the optional properties are not initialize, setting default values to them. Is it right? If yes, when only set properties  `resourcePath`, `resourceType` and `interfaces` to `resource` which as a argument of `register`, the method should not work, but it works. Can you help me make it clear?

**Comment by zolkis** [comment]
For interfaces, when applications do not provide any value, implementations (by OCF definition) MUST implement at least `oic.if.baseline`. So this is not mandatory from an app, but you are right this should be explicitly mentioned in the spec -- action point 1 for me.

In addition to path, type and interfaces, either `properties` or `links` (exactly one of them) SHOULD also be specified, otherwise there is no point in creating the resource. (I should change the default value of `properties` from `{}` to `undefined` -- action point 2 for me).

Except the rule above, basically all resource properties MUST be present: `secure`, `discoverable` and `observable` default to `true`, `slow` defaults to `false`. `mediaTypes` MAY be an empty array. This requires no change in the spec.

**Comment by wanghongjuan** [comment]
@zolkis Thanks for your clarification. We are using #28 to track the third point.
 I just find [`create`](https://github.com/01org/iot-js-api/blob/master/api/ocf/client.md#create) method has same situation as `register`.

**Comment by wanghongjuan** [comment]
@zolkis I find the `register` method has been updated, but the [`create`](https://github.com/01org/iot-js-api/blob/master/api/ocf/client.md#create) method not. Could you please recheck it? Not sure if you skip or not. :)

**Comment by zolkis** [comment]
We don't need to force client apps to provide all resource details, since `register()` takes care of them.

The `create()` method on the client side must only specify the absolute minimum properties for a resource to be registered by the server, that is a resource path and type. 

The `create` request will have an `oncreate` handler on server side, which calls `register()`, which ensures that any resource registered with the OCF network has a valid set of properties and provides default values if needed.

Therefore IMHO the `create()` method can be left as it is.
