### ISSUE TITLE
Unclear part for client.create()

### ISSUE THREAD

**Issue by wind-rider** [01org/iot-js-api#33]
In https://github.com/01org/iot-js-api/blob/master/api/ocf/client.md#41-the-createresource-target-method, there is written that `resource` is a `Resource` object in `client.create( ... )`.

According to https://github.com/01org/iot-js-api/blob/master/api/ocf/client.md#13-the-resource-dictionary, a `Resource` object has a lot of properties that are obligatory.

However, `resource` in `client.create( ... )` has only 2 obligatory properties, and it has `resourceType` instead of `resourceType*s*`.

Could anybody help me understand how this works and how to model it in Typescript?

**Comment by wind-rider** [comment]
In https://github.com/otcshare/iotivity-node/blob/master/js/high-level-resource-creation-client.js#L51, `resourceType` is not used with a `string` type. Instead `resourceTypes` is used with a `string[]` type.

Is the spec outdated or is the example wrong?

**Comment by zolkis** [comment]
Will check tomorrow (it's almost 1am here :).

**Comment by wanghongjuan** [comment]
Hi, @wind-rider there is another issue #27 which @zolkis explained why the `create` method has only 2 obligatory properties. 
For the `resourceType`, in https://github.com/01org/iot-js-api/blob/master/api/ocf/client.md#41-the-createresource-target-method descibes `The resource argument is a Resource object. It should contain at least the following properties (other resource properties may also be specified): resourcePath and resourceType`, however, the [`Resource`](https://github.com/01org/iot-js-api/blob/master/api/ocf/client.md#resource) object has property `resourceTypes`, instead of `resourceType`, this is doubtful.

**Comment by zolkis** [comment]
Fixed, please check if OK.
